### ISSUE TITLE
Automating Calculator on Windows10

### ISSUE THREAD

**Issue by reshma79** [JamesMGreene/twin#1]
Hi,

I am trying to identify calculator on windows 10 operating system using TWIN. code :

app.open("calc", null);

opens the calculator but code :

Window window = app.getWindow();

does not identify the application and throws exception as

org.ebayopensource.twin.TwinNoSuchElementException: Found no children of Desktop(id=null)@null matching controlType=Window after waiting 30.0

Any help in solving this would be appreciated.

Regards,
Reshma.

**Comment by JamesMGreene** [comment]
@reshma79:

I have only used TWIN for a small bit of research myself.  I don't have any valuable experience with it to offer, nor did I ever change any of its underlying code.  I simply saved a copy of it from its [old home on Google Code](https://code.google.com/archive/p/twin/) to live on GitHub.

You may want to consider using something like [White](https://github.com/TestStack/White) or [Coded UI](https://msdn.microsoft.com/en-us/library/dd286726.aspx).

HTH, best of luck!
